#!/usr/bin/env bash

set -e

aws s3 cp s3://$BUILD_BUCKET/env /etc/environment --region us-east-2

_INTERNAL_IP=$(curl -s http://169.254.169.254/latest/meta-data/local-ipv4)

echo "" >> /etc/environment
echo "INTERNAL_IP=$_INTERNAL_IP" >> /etc/environment
echo "" >> /etc/environment
echo "RELEASE_NAME=web_app@$_INTERNAL_IP" >> /etc/environment
